version: 0.2
phases:
  install:
    commands:
      # Install all dependencies (including dependencies for running tests)
      - cd ./dependencies/nodejs 
      - npm install
      - cd ../../
  pre_build:
    commands:
      # Discover and run unit tests in the '__tests__' directory
      #- npm run test
      # Remove all unit tests to reduce the size of the package that will be ultimately uploaded to Lambda
      #- rm -rf ./__tests__
      # Remove all dependencies not needed for the Lambda deployment package (the packages from devDependencies in package.json)
      #- npm prune --production
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      #- aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
      - aws cloudformation package --template-file ./src/template.yml --s3-bucket aws-sam-ticketappdeployment --output-template-file out.yml --s3-prefix ticketapp
  post_build:
    commands:
    - cp ./src/template.yml .

artifacts:
  type: zip
  files:
    - template.yml #for next stage for deploying
    - out.yml