version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ticketapp"
s3_bucket = "aws-sam-ticketappdeployment"
s3_prefix = "ticketapp"
region = "eu-central-1"
profile = "erick"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
